sudo: required
services:
  - docker
script: docker build -t jagoancoind . && ( docker run jagoancoind -version | tee /dev/stderr | grep -q $(cat VERSION) ) 2>&1
notifications:
  email:
    on_success: never
